### ISSUE TITLE
コードの変更をGitHubにプッシュしたら、その変更をEC2でも反映するようにする

### ISSUE THREAD

**Issue by kaitokimuraofficial** [kaitokimuraofficial/blog-infra#26]
## What
**Describe the solution you'd like**

- [x] GitHubを活用したセキュアなデプロイ方法について調べる
- [x] 実装する

## Why
**Describe related problems**

## Others
**Describe what you want to describe**

**Comment by kaitokimuraofficial** [comment]
# リビジョンの作成

**Comment by kaitokimuraofficial** [comment]
## 2. [CodeDeployのリビジョンにアプリケーション仕様ファイル(`AppSpec`)を追加する](https://docs.aws.amazon.com/ja_jp/codedeploy/latest/userguide/application-revisions-appspec-file.html)

アプリケーションリビジョンのソースファイルを宛先にマッピングしたり、デプロイ用のスクリプトを EC2に実行したりCodeDeployするには**`AppSpec`ファイルが必須** 。各リビジョンには 1 つの AppSpec ファイルのみを含める必要がある。

### リビジョンに AppSpec ファイルを追加するには：
1. テンプレートをコピー
2. 必要に応じてテンプレートを変更
3. YAML 検証を使用して、AppSpecファイルの有効性を確認
4. リビジョンの**ルートディレクトリ**にappspec.ymlとしてファイルを保存
5. リビジョンを Amazon S3またはGitHubにプッシュ


**AppSpec 手順を含む EC2/オンプレミスデプロイ用の ファイルテンプレート**

```yml
# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines in this template starting with the hashtag symbol are 
#   instructional comments and can be safely left in the file or 
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux, 
#   Red Hat Enterprise Linux (RHEL), or Ubuntu Server  
#   instances.
# Specify "os: windows" if this revision targets Windows Server instances.
# (You cannot specify both "os: linux" and "os: windows".)
os: linux 
# os: windows
# During the Install deployment lifecycle event (which occurs between the 
#   BeforeInstall and AfterInstall events), copy the specified files 
#   in "source" starting from the root of the revision's file bundle 
#   to "destination" on the Amazon EC2 instance.
# Specify multiple "source" and "destination" pairs if you want to copy 
#   from multiple sources or to multiple destinations.
# If you are not copying any files to the Amazon EC2 instance, then remove the
#   "files" section altogether. A blank or incomplete "files" section
#   may cause associated deployments to fail.
files:
  - source: 
    destination:
  - source:
    destination:
# For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
#   you can specify a "permissions" 
#   section here that describes special permissions to apply to the files 
#   in the "files" section as they are being copied over to 
#   the Amazon EC2 instance.
#   For more information, see the documentation.
# If you are deploying to Windows Server instances,
#   then remove the 
#   "permissions" section altogether. A blank or incomplete "permissions"
#   section may cause associated deployments to fail.
permissions:
  - object:
    pattern:
    except:
    owner:
    group:
    mode: 
    acls:
      -
    context:
      user:
      type:
      range:
    type:
      -
# If you are not running any commands on the Amazon EC2 instance, then remove 
#   the "hooks" section altogether. A blank or incomplete "hooks" section
#   may cause associated deployments to fail.
hooks:
# For each deployment lifecycle event, specify multiple "location" entries 
#   if you want to run multiple scripts during that event.
# You can specify "timeout" as the number of seconds to wait until failing the deployment 
#   if the specified scripts do not run within the specified time limit for the 
#   specified event. For example, 900 seconds is 15 minutes. If not specified, 
#   the default is 1800 seconds (30 minutes).
#   Note that the maximum amount of time that all scripts must finish executing 
#   for each individual deployment lifecycle event is 3600 seconds (1 hour). 
#   Otherwise, the deployment will stop and CodeDeploy will consider the deployment
#   to have failed to the Amazon EC2 instance. Make sure that the total number of seconds 
#   that are specified in "timeout" for all scripts in each individual deployment 
#   lifecycle event does not exceed a combined 3600 seconds (1 hour).
# For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
#   you can specify "runas" in an event to
#   run as the specified user. For more information, see the documentation.
#   If you are deploying to Windows Server instances,
#   remove "runas" altogether.
# If you do not want to run any commands during a particular deployment
#   lifecycle event, remove that event declaration altogether. Blank or 
#   incomplete event declarations may cause associated deployments to fail.
# During the ApplicationStop deployment lifecycle event, run the commands 
#   in the script specified in "location" starting from the root of the 
#   revision's file bundle.
  ApplicationStop:
    - location: 
      timeout:
      runas:
    - location: 
      timeout:
      runas: 
# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: 
      timeout:
      runas: 
    - location: 
      timeout:
      runas:
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  AfterInstall:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
# During the ApplicationStart deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
# During the ValidateService deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ValidateService:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
```

**Comment by kaitokimuraofficial** [comment]
# 実際にやってみた

```yml
version: 0.0
os: linux 
files:
  - source: assets
    destination: /usr/share/html/nginx
  - source: index/html
    destination: /usr/share/html/nginx
```
するとエラーになった
(`/var/log/aws/codedeploy-agent/codedeploy-agent.log`)

```txt
2024-08-14T21:08:41 ERROR [codedeploy-agent(52804)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: Error during certificate verification on codedeploy endpoint https://codedeploy-commands.ap-northeast-1.amazonaws.com
2024-08-14T21:08:41 ERROR [codedeploy-agent(52804)]: Error validating the SSL configuration: Invalid server certificate
2024-08-14T21:08:41 ERROR [codedeploy-agent(52804)]: booting child: error during start or run: SystemExit - Stopping CodeDeploy agent due to SSL validation error. -/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:65:in `abort'
2024-08-14T21:08:41 ERROR [codedeploy-agent(52804)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:98:in `exit'
```
